name: yate_diamond
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0     # Para la base de datos local
  path: ^1.8.3        # Para las rutas de los archivos
  signature: ^5.5.0
  supabase_flutter: ^2.0.0  # Para las firmas al final de los checklists
  syncfusion_flutter_pdfviewer: ^33.2.12
  device_info_plus: ^12.4.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.5
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ¡AQUÍ ESTÁ LA CORRECCIÓN CLAVE PARA TUS IMÁGENES!
  # Asegúrate de mantener estos espacios exactos (2 espacios antes de assets, 4 antes del guion)
  assets:
    - lib/img/
